class GenreGroups:
    @staticmethod
    def get_genres():
        # Top 300-ish Genres Related to Pop
        pop_genres = [
            'pop',
            'dance pop',
            'post-teen pop',
            'talent show',
            'boy band',
            'uk pop',
            'alt z',
            'pop dance',
            'edm',
            'melodipop',
            'r&b',
            'mexican pop',
            'swedish idol pop',
            'deep dance pop',
            'k-pop',
            'ukrainian pop',
            'electropop',
            'japanese teen pop',
            'chinese idol pop',
            'latin pop',
            'finnish dance pop',
            'pop argentino',
            'social media pop',
            'spanish pop',
            'classic k-pop',
            'taiwan idol pop',
            'danish pop',
            'latin arena pop',
            'argentine telepop',
            'p-pop',
            'belarusian pop',
            'teen pop',
            'japanese r&b',
            'german pop',
            'australian pop',
            'finnish pop',
            'indie poptimism',
            'reggae uruguayo',
            'hyperpop',
            'c-pop girl group',
            'spanish pop rock',
            'hungarian pop',
            'thai indie',
            'city pop',
            'swedish pop',
            'tatar pop',
            'latin alternative',
            'russian pop',
            'rock en espanol',
            'chinese electropop',
            'bulgarian pop',
            'polish pop',
            'russian dance pop',
            'dutch idol pop',
            'redneck',
            'vinahouse',
            'latin rock',
            'greek pop',
            'pinoy idol pop',
            'musica catalana',
            'ukrainian rock',
            'gospel amapiano',
            'deep turkish pop',
            'korean hyperpop',
            'scream rap',
            'thai teen pop',
            'swiss pop',
            'nightcore',
            'lagu sabahan',
            'trap metal italiana',
            'mongolian pop',
            'russian emo rap',
            'japanese hyperpop',
            'scandipop',
            'lithuanian pop',
            'australian electropop',
            'k-pop boy group',
            'escape room',
            'japanese viral pop',
            'country rap',
            'variete francaise',
            'indie salvadoreno',
            'reggae cristao',
            'montenegrin pop',
            'ukrainian folk rock',
            'emo rap italiano',
            'japanese dance pop',
            'emo trap italiana',
            'modern alternative pop',
            'classic portuguese pop',
            'moldovan pop',
            'british soul',
            'latinx alternative',
            'hyperpop italiano',
            'cerkes muzikleri',
            'reggae catala',
            'south african pop',
            'thai rock',
            'macedonian pop',
            'maltese pop',
            'bosnian indie',
            'reggae boliviano',
            'europop',
            'pink noise',
            'yakut pop',
            'italian indie pop',
            'pop paraguayo',
            'antiviral pop',
            'spanish rock',
            'polish reggae',
            'swedish electropop',
            'kazakh pop',
            'australian r&b',
            'australian talent show',
            'necrotrap',
            'geinin song',
            'cape town indie',
            'festigal',
            'urban contemporary',
            'graz indie',
            'thai indie pop',
            'malaysian hip hop',
            'czech pop rock',
            'rap geek',
            'mestissatge',
            'tropical house',
            'turkish pop',
            'gospel papiamento',
            'persian pop',
            'milan indie',
            'puerto rican pop',
            'lagu karo',
            'pop electronico',
            'russian alt pop',
            'antideutsche',
            'azeri pop',
            'la pop',
            'russian trap metal',
            'thai folk rock',
            'austrian pop',
            'estonian pop',
            'mexican rock',
            'tamil hip hop',
            'belgian pop',
            'tunisian pop',
            'pop nacional',
            'new jack smooth',
            'german indie pop',
            'slaskie piosenki',
            'japanese trap',
            'pop peruano',
            'thai pop',
            'christian afrobeat',
            'uzbek pop',
            'zambian pop',
            'italian pop',
            'okinawan pop',
            'pop edm',
            'contemporary r&b',
            'bolivian rock',
            'israeli mediterranean',
            'indie campechano',
            'uae indie',
            'guadalajara indie',
            'turbo folk',
            'turkmen pop',
            'korean city pop',
            'russian dance',
            'latin viral pop',
            'kolsche karneval',
            'mexican indie',
            'neomelodici',
            'swedish soul',
            'cedm',
            'armenian pop',
            'new wave pop',
            'idol kayo',
            'lagu sasak',
            'brazilian ska',
            'zxc',
            'schlager',
            'ska argentino',
            'levenslied',
            'jordanian pop',
            'leon gto indie',
            'japanese electropop',
            'danish pop rock',
            'albanian pop',
            'covertronica',
            'elektropunk',
            'latvian pop',
            'colombian rock',
            'canadian electropop',
            'sulawesi indie',
            'glitchcore',
            'sertanejo gospel',
            'emo trap en espanol',
            'japanese soul',
            'kokborok pop',
            'volkspop',
            'alberta country',
            'guatemalan pop',
            'bodo pop',
            'nerdcore brasileiro',
            'kosovan pop',
            'pop virale italiano',
            'kompa chretien',
            'tajik pop',
            'turkce trap metal',
            'pov: indie',
            'myanmar indie',
            'junior songfestival',
            'japanese pop rap',
            'hyperpop en espanol',
            'italian hip hop',
            'italian pop rock',
            'r&b italiano',
            'ugandan gospel',
            'greenlandic pop',
            'kavkaz',
            'shaabi',
            'rap galego',
            'chinese manyao',
            'australian alternative pop',
            'south borneo indie',
            'pop lgbtq+ brasileira',
            'russian viral pop',
            'venezuelan indie',
            'chalga',
            'pop teen brasileiro',
            'louange',
            'shimmer pop',
            'assyrian pop',
            'indie pop rap',
            'game mood',
            'magyar retro dance',
            'modern bollywood',
            'ghanaian gospel',
            'dikir barat',
            'classic j-pop',
            'rock mineiro',
            'japanese chill rap',
            'contemporary country',
            'indonesian ska',
            'burmese pop',
            'african rock',
            'mundart',
            'albanian rock',
            'ska catala',
            'russian reggae',
            'k-pop reality show',
            'west coast reggae',
            'josei rap',
            'musica ponta-grossense',
            'pop chileno',
            'karneval',
            'country pop',
            'j-rap',
            'hopebeat',
            'canadian pop',
            'fogo pentecostal',
            'german pop rock',
            'kyrgyz pop',
            'russian indie',
            'lagu lampung',
            'russelater',
            'volksmusik',
            'lagu aceh',
            'circassian folk',
            'transpop',
            'paraguayan indie',
            'lagu jambi',
            'volkstumliche musik',
            'fotbollslatar',
            'tontipop',
            'candy pop',
            'new tejano',
            'modern country rock',
            'belarusian hip hop',
            'indonesian hyperpop'
        ]

        # Top 300-ish Genres Related to Rap
        rap_genres = [
            'rap',
            'trap',
            'pop rap',
            'southern hip hop',
            'hip hop',
            'atl hip hop',
            'gangster rap',
            'dirty south rap',
            'melodic rap',
            'r&b',
            'east coast hip hop',
            'conscious hip hop',
            'underground hip hop',
            'dance pop',
            'queens hip hop',
            'new orleans rap',
            'hardcore hip hop',
            'urban contemporary',
            'mississippi hip hop',
            'australian hip hop',
            'australian trap',
            'deep underground hip hop',
            'asian american hip hop',
            'miami hip hop',
            'texas latin rap',
            'houston rap',
            'military rap',
            'maga rap',
            'dfw rap',
            'czech hip hop',
            'nashville hip hop',
            'chicago rap',
            'czsk hip hop',
            'nz gangsta rap',
            'danish hip hop',
            'baton rouge rap',
            'nz hip hop',
            'punjabi hip hop',
            'minnesota hip hop',
            'ohio hip hop',
            'old school atlanta hip hop',
            'hip pop',
            'cali rap',
            'detroit trap',
            'oakland hip hop',
            'tennessee hip hop',
            'russian trap',
            'west coast trap',
            'polish hip hop',
            'san diego rap',
            'zim hip hop',
            'czsk viral pop',
            'korean drill',
            'slovak hip hop',
            'trap cristiano',
            'albanian hip hop',
            'cologne hip hop',
            'desi trap',
            'polish viral rap',
            'bc underground hip hop',
            'baltimore hip hop',
            'australian indigenous hip hop',
            'korean underground rap',
            'desi hip hop',
            'dutch hip hop',
            'polynesian hip hop',
            'finnish hip hop',
            'trap colombiano',
            'dirty texas rap',
            'german hip hop',
            'south african hip hop',
            'indie pop rap',
            'lgbtq+ hip hop',
            'swiss hip hop',
            'russian hip hop',
            'kansas city hip hop',
            'norwegian hip hop',
            'romanian trap',
            'hyphy',
            'kyrgyz hip hop',
            'deep southern trap',
            'armenian hip hop',
            'flint hip hop',
            'futuristic swag',
            'alabama rap',
            'hindi hip hop',
            'canadian hip hop',
            'sichuanese hip hop',
            'detroit hip hop',
            'korean trap',
            'bay area hip hop',
            'anime rap',
            'marathi hip hop',
            'crunk',
            'philly rap',
            'rap cristiano',
            'christlicher rap',
            'anime drill',
            'toronto rap',
            'turkish hip hop',
            'rap uruguayo',
            'ukrainian hip hop',
            'pop urbaine',
            'german drill',
            'central asian hip hop',
            'greek trap',
            'israeli trap',
            'french hip hop',
            'hawaiian hip hop',
            'rap conscient',
            'rap sardegna',
            'polish trap',
            'canadian indigenous hip hop',
            'arabic hip hop',
            'hip hop quebecois',
            'christian trap',
            'trap mexicano',
            'north carolina hip hop',
            'belarusian hip hop',
            'josei rap',
            'christian hip hop',
            'rap marseille',
            'west australian hip hop',
            'chopped and screwed',
            'j-rap',
            'argentine hip hop',
            'gospel rap',
            'afrikaans hip hop',
            'japanese drill',
            'south carolina hip hop',
            'rap uliczny',
            'london rap',
            'russian gangster rap',
            'trap catala',
            'milwaukee hip hop',
            'rap motywacja',
            'rap catala',
            'neoperreo',
            'serbian hip hop',
            'kasi rap',
            'virginia hip hop',
            'scam rap',
            'turkish trap',
            'croatian hip hop',
            'uk hip hop',
            'rap canario',
            'kansas hip hop',
            'k-rap',
            'russian grime',
            'gambian hip hop',
            'trap italiana',
            'russian drill',
            'chinese hip hop',
            'rap cristao',
            'rap feminino nacional',
            'afghan rap',
            'chicago drill',
            'gengetone',
            'pinoy alternative rap',
            'taiwan hip hop',
            'german alternative rap',
            'atlantic canada hip hop',
            'st louis rap',
            'suomirap',
            'polish viral pop',
            'indiana hip hop',
            'native american hip hop',
            'rap gaucho',
            'urbano espanol',
            'romanian rap',
            'reggaeton cristiano',
            'israeli hip hop',
            'rap antillais',
            'hamburg hip hop',
            'slow game',
            'balkan trap',
            'swedish hip hop',
            'gothenburg hip hop',
            'pittsburgh rap',
            'mexican hip hop',
            'macedonian hip hop',
            'psychokore',
            'denver rap',
            'rap latina',
            'greek hip hop',
            'nyc rap',
            'australian underground hip hop',
            'japanese trap',
            'bulgarian hip hop',
            'polish drill',
            'drill',
            'funk evangelico',
            'german underground rap',
            'thai hip hop',
            'manchester hip hop',
            'rap francais',
            'rap underground mexicano',
            'hjemmesnekk',
            'italian hip hop',
            'balkan drill',
            'rap femenino mexicano',
            'antilliaanse rap',
            'icelandic hip hop',
            'russian pixel',
            'horrorcore',
            'rap alagoano',
            'bounce',
            'guatemalan pop',
            'meme rap',
            'pakistani hip hop',
            'brooklyn drill',
            'country rap',
            'zambian hip hop',
            'trap queen',
            'trap chileno',
            'uk dancehall',
            'kannada hip hop',
            'dutch rap pop',
            'chicano rap',
            'drill italiana',
            'trap cristao',
            'khmer hip hop',
            'german reggae',
            'trap argentino',
            'rap ivo',
            'new jersey rap',
            'rap salvadoreno',
            'uzbek hip hop',
            'swedish dancehall',
            'czech drill',
            'ugandan hip hop',
            'rap baiano',
            'colombian hip hop',
            'kazakh hip hop',
            'afroswing',
            'indonesian hip hop',
            'urbano mexicano',
            'malawian hip hop',
            'florida rap',
            'reggae rock',
            'rap kreyol',
            'kids hip hop',
            'balkan hip hop',
            'trap dominicano',
            'kurdish hip hop',
            'grime',
            'bayerischer rap',
            'norwegian pop rap',
            'swedish pop rap',
            'finnish trap',
            'new jersey underground rap',
            'viral rap',
            'swedish trap',
            'swedish gangsta rap',
            'malaysian tamil pop',
            'jewish hip hop',
            'greek drill',
            'chicago bop',
            'rap norteno chileno',
            'memphis hip hop',
            'iowa hip hop',
            'nederreggae',
            'r&b francais',
            'polish alternative rap',
            'east coast reggae',
            'pop catracho',
            'swedish trap pop',
            'lithuanian hip hop',
            'ottawa rap',
            'french reggae',
            'slovenian hip hop',
            'kenyan pop',
            'trap venezolano',
            'burundian pop',
            'greek fem rap',
            'nordnorsk rap',
            'swedish reggae',
            'dancehall guyanaise',
            'brazilian hip hop',
            'indie hip hop',
            'asakaa',
            'sacramento hip hop',
            'ritmo kombina',
            'redneck',
            'estonian hip hop',
            'pinoy trap',
            'seychelles pop',
            'rap genovese',
            'urbano chileno',
            'r&b en espanol',
            'canadian trap',
            'idaho hip hop',
            'new york drill',
            'malaysian hip hop',
            'alaska hip hop',
            'perth hip hop',
            'rap toscana',
            'alberta hip hop',
            'kentucky hip hop',
            'trap kreyol'
        ]

        # Top 300-ish Genres Related to EDM
        edm_genres = [
            'edm',
            'pop dance',
            'electro house',
            'dutch house',
            'progressive electro house',
            'complextro',
            'brostep',
            'big room',
            'progressive house',
            'electronic trap',
            'house',
            'dutch edm',
            'melbourne bounce',
            'slap house',
            'sky room',
            'dance pop',
            'pop',
            'canadian electronic',
            'future house',
            'uk dance',
            'mashup',
            'musica eletronica gospel',
            'future bounce',
            'australian dance',
            'electronica cristiana',
            'deep pop edm',
            'pop edm',
            'deep filthstep',
            'new rave',
            'moldovan pop',
            'kawaii future bass',
            'gaming edm',
            'covertronica',
            'filthstep',
            'alternative dance',
            'russian edm',
            'dubstep product',
            'christian dance',
            'electronic rock',
            'dance-punk',
            'bass trap',
            'pinoy edm',
            'indonesian edm',
            'belgian edm',
            'neo-synthpop',
            'japanese electropop',
            'japanese dance pop',
            'rock nica',
            'dariacore',
            'nordic house',
            'vocal trance',
            'russian rave',
            'cedm',
            'traprun',
            'dutch trance',
            'german dance',
            'kawaii edm',
            'tekk',
            'dubstep',
            'aggressive phonk',
            'russian trap metal',
            'speed house',
            'ukrainian edm',
            'pink noise',
            'industrial pop',
            'swedish electropop',
            'swiss pop',
            'scream rap',
            'big beat',
            'electro trash',
            'covertrance',
            'swedish synthpop',
            'arab trap',
            'japanese edm',
            'dance rock',
            'stutter house',
            'electrofox',
            'aussietronica',
            'sinhala edm',
            't-pop girl group',
            'deep uplifting trance',
            'viet edm',
            'swedish tropical house',
            'indian edm',
            'bitpop',
            'australian electropop',
            'russian synthpop',
            'super eurobeat',
            'elektropunk',
            'swedish synth',
            'trance',
            'finnish edm',
            'japanese vtuber',
            'k-pop boy group',
            'moombahton',
            'saxophone house',
            'electropowerpop',
            'sulawesi indie',
            'electroclash',
            'necrotrap',
            'solipsynthm',
            'pop house',
            'deep dance pop',
            'glitch hop',
            'gym phonk',
            'ebm',
            'j-pop boy group',
            'nederlandse hardstyle',
            'melbourne bounce international',
            'halftime dnb',
            'cape town indie',
            'experimental bass',
            'future funk',
            'breakbeat',
            'deep breakcore',
            'europop',
            'dark synthpop',
            'remix product',
            'doujin',
            'south borneo indie',
            'spanish synthpop',
            'nightcore',
            'indie liguria',
            'futurepop',
            'gaming dubstep',
            'k-pop reality show',
            'rave',
            'new beat',
            'russelater',
            'dark clubbing',
            'ukrainian phonk',
            'german trance',
            'pop electronico',
            'mashcore',
            'samurai trap',
            'filter house',
            'cantaditas',
            'coventry indie',
            'singaporean electronic',
            'rap rock',
            'dark electro',
            'canadian electropop',
            'bossbeat',
            'eurodance',
            'k-pop',
            'swedish eurodance',
            'electro-industrial',
            'gospel amapiano',
            'dakke dak',
            'proto-hyperpop',
            'deep neo-synthpop',
            'synthpop',
            'funk mexicano',
            'j-division',
            'c-pop girl group',
            'anime phonk',
            'uae indie',
            'classic k-pop',
            'deep big room',
            'indietronica',
            'escape room',
            'deep eurodance',
            'rebel blues',
            'maltese pop',
            'spanish electropop',
            'deep vocal house',
            'japanese viral pop',
            'hyperpop',
            'purple sound',
            'magyar retro dance',
            'bubblegum bass',
            'mexican rock',
            'post-punk colombiano',
            'funktronica',
            'turkce trap metal',
            'junior songfestival',
            'riddim dubstep',
            'deep tropical house',
            'belgian new wave',
            'progressive trance',
            'hands up',
            'reggae boliviano',
            'industrial hip hop',
            'chinese idol pop',
            'antideutsche',
            'russian indie rock',
            'taiwan idol pop',
            'breakcore',
            'russian dance pop',
            'musica quintanarroense',
            'eurobeat',
            'classic j-pop',
            'chill phonk',
            'candy pop',
            'anime latino',
            'strut',
            'japanese hyperpop',
            'latvian rock',
            'nz dnb',
            'tropical house',
            'nu gabber',
            'rhythm game',
            'epa dunk',
            'drift phonk',
            'finnish electro',
            'south african punk',
            'mexican edm',
            'shimmer pop',
            'minimal wave',
            'electropop',
            'vocaloid',
            'singeli',
            'danish electronic',
            'geinin song',
            'shibuya-kei',
            'russian pop',
            'korean hyperpop',
            'melodipop',
            'deathstep',
            'cuban electronic',
            'scandipop',
            'k-pop girl group',
            'indie campechano',
            'grimewave',
            'indonesian idol pop',
            'reggae uruguayo',
            'dusseldorf indie',
            'talent show',
            'livetronica',
            'romanian pop',
            'okinawan pop',
            'early synthpop',
            'post-teen pop',
            'dark electro-industrial',
            'shojo',
            'psybass',
            'czech pop rock',
            'korean electronic',
            'bouncy house',
            'aggrotech',
            'south african dnb',
            'gym hardstyle',
            'draga',
            'rock en espanol',
            'slovak rock',
            'belarusian pop',
            'new romantic',
            'latin rock',
            'mexican indie',
            'touhou',
            'deep hardcore',
            'polish reggae',
            'experimental club',
            'russian indie',
            'japanese jazztronica',
            'puglia indie',
            'popwave',
            'hardcore techno',
            'ukrainian folk rock',
            'nz electronic',
            'future bass',
            'japanese progressive house',
            'scenecore',
            'antiviral pop',
            'brazilian ska',
            'japanese new wave',
            'industrial rock',
            'denpa-kei',
            'bolivian rock',
            'dub punk',
            'barbadian pop',
            'chinese electropop',
            'raggatek',
            'power noise',
            'j-pop',
            'classic dubstep',
            'vapor twitch',
            'neo-industrial rock',
            'classic romanian pop',
            'bulgarian pop',
            'metropopolis',
            'boy band',
            'vapor house',
            'russian emo rap',
            'dortmund indie',
            'new wave',
            'anime cv',
            'talentkonkurrence',
            'russian trance',
            'nu skool breaks',
            'chilean hardcore',
            'instrumental grime',
            'rap metalcore',
            'ukrainian rock',
            'tontipop',
            'thai indie',
            'neue deutsche harte',
            'finnish dance pop',
            'belgian dance',
            'happy hardcore'
        ]

        # Top 300-ish Genres Related to Country
        country_genres = [
            "country",
            "country road",
            "contemporary country",
            "country rock",
            "classic country pop",
            "modern country rock",
            "country dawn",
            "classic oklahoma country",
            "outlaw country",
            "nashville sound",
            "classic iskelma",
            "classic finnish pop",
            "dansktop",
            "classic texas country",
            "pop nacional antigas",
            "konkani pop",
            "szanty",
            "czech country",
            "classic israeli pop",
            "classic norwegian pop",
            "grunneger muziek",
            "neo soul",
            "classic icelandic pop",
            "marathi devotional",
            "cantautor",
            "uyghur pop",
            "musica valenciana",
            "classic danish pop",
            "folclore portugues",
            "classic uk pop",
            "friese muziek",
            "mpb",
            "flemish folk",
            "hare krishna",
            "magyar musicalek",
            "folk rock italiano",
            "musica goiana",
            "mollywood",
            "afrikaans folk",
            "vintage cantonese pop",
            "anti-folk",
            "esperanto",
            "kashmiri pop",
            "kurdish folk",
            "nl folk",
            "bubblegum pop",
            "xhosa",
            "classic swedish pop",
            "vintage dutch pop",
            "jovem guarda",
            "mexican rock-and-roll",
            "italian folk",
            "deep latin christian",
            "folk siciliana",
            "kleinkunst",
            "waiata maori",
            "chanson quebecois",
            "nuevo folklore mexicano",
            "czech folk",
            "ulkucu sarkilar",
            "austin singer-songwriter",
            "geek folk",
            "pop romantico",
            "austin americana",
            "musica canaria",
            "classic italian pop",
            "musica menorquina",
            "new orleans americana",
            "mantra",
            "musica lombarda",
            "karadeniz turkuleri",
            "classic czech pop",
            "ryukyu ongaku",
            "neo-traditional bluegrass",
            "musica costarricense",
            "neo honky tonk",
            "palestinian alternative",
            "czech folk rock",
            "israeli singer-songwriter",
            "swamp pop",
            "black americana",
            "a cappella",
            "classic french pop",
            "filmi",
            "nederpop",
            "classic soul",
            "classic latvian pop",
            "bhajan",
            "musica occitana",
            "western americana",
            "otroske pesmice",
            "south african country",
            "canadian singer-songwriter",
            "laiko",
            "sunshine pop",
            "classic polish pop",
            "canadian country",
            "classic nz pop",
            "muzica usoara",
            "acoustic punk",
            "french rock",
            "irish rebel song",
            "syrian pop",
            "italian adult pop",
            "musica mapuche",
            "singer-songwriter",
            "memphis americana",
            "native american contemporary",
            "musica cearense",
            "wrock",
            "palestinian pop",
            "cape verdean folk",
            "rock catala",
            "musica paranaense",
            "classic luk thung",
            "sufi",
            "kurdish rock",
            "kayokyoku",
            "goralski",
            "german ccm",
            "classic greek pop",
            "musica nortena chilena",
            "classic greek rock",
            "mezmur",
            "musica popular uruguaya",
            "tropicalia",
            "nordnorsk musikk",
            "greek swing",
            "bangla pop",
            "j-acoustic",
            "lagu maluku",
            "turkish singer-songwriter",
            "north carolina roots",
            "dabke",
            "nova mpb",
            "spanish folk",
            "musica sarda",
            "folk rock",
            "georgian pop",
            "michigan folk",
            "austropop",
            "turkish psych",
            "merseybeat",
            "rio grande do sul indie",
            "musica juiz-forana",
            "classic ukrainian pop",
            "arabesk",
            "ranchera",
            "auteur-compositeur-interprete quebecois",
            "cypriot pop",
            "concurso de talentos argentino",
            "australian blues",
            "nashville americana",
            "cymraeg",
            "wyoming roots",
            "mariachi cristiano",
            "indie folk italiano",
            "roots rock",
            "montana roots",
            "german singer-songwriter",
            "rock of gibraltar",
            "maghreb",
            "streektaal",
            "musica brasiliense",
            "mellow gold",
            "lldm",
            "chicago soul",
            "southern soul",
            "northern soul",
            "poezja spiewana",
            "classic girl group",
            "canadian folk",
            "ghazal",
            "novos talentos brasileiros",
            "talentos brasileiros",
            "australian americana",
            "belo horizonte indie",
            "musiikkia lapsille",
            "musica timor-leste",
            "ilocano pop",
            "kentucky roots",
            "yacht rock",
            "philly soul",
            "nouvelle chanson francaise",
            "pakistani pop",
            "classic cantopop",
            "svensk progg",
            "world",
            "ostschlager",
            "nova musica carioca",
            "oaxaca indie",
            "assamese pop",
            "cantautor catala",
            "taraneem",
            "west bengali pop",
            "canadian blues",
            "laulaja-lauluntekija",
            "folk brasileiro",
            "garhwali pop",
            "uyghur folk",
            "via",
            "israeli rock",
            "indie cordoba",
            "sinhala pop",
            "new mexico music",
            "scottish singer-songwriter",
            "khmer",
            "hungarian folk",
            "jain bhajan",
            "dutch pop",
            "musica mogiana",
            "classic pakistani pop",
            "classic sinhala pop",
            "new americana",
            "classic arab pop",
            "sung poetry",
            "tan co"
        ]

        # Top 300-ish Genres Related to Jazz
        jazz_genres = [
            "jazz",
            "bebop",
            "contemporary post-bop",
            "hard bop",
            "cool jazz",
            "jazz saxophone",
            "jazz piano",
            "jazz trumpet",
            "jazz fusion",
            "vocal jazz",
            "contemporary jazz",
            "jazz funk",
            "swing",
            "jazz drums",
            "jazz quartet",
            "soul jazz",
            "ecm-style jazz",
            "straight-ahead jazz",
            "electric bass",
            "free jazz",
            "avant-garde jazz",
            "swedish jazz orkester",
            "african-american classical",
            "tin pan alley",
            "jazz brass",
            "samba-jazz",
            "jazz trombone",
            "tango",
            "jazz violin",
            "harlem renaissance",
            "jazz catala",
            "yiddish folk",
            "schrammelmusik",
            "spanish jazz",
            "yemeni traditional",
            "ethiopian traditional",
            "jazz flute",
            "czech swing",
            "scottish jazz",
            "russian jazz",
            "jazz vibraphone",
            "harmonica jazz",
            "tajik traditional",
            "ethnomusicology",
            "lao traditional",
            "traditional southern folk",
            "hula",
            "cambodian traditional",
            "violao",
            "french jazz",
            "polca paraguaya",
            "jazz blues",
            "vaudeville",
            "music hall",
            "british dance band",
            "oud",
            "deep delta blues",
            "cante flamenco",
            "big band",
            "jazz trio",
            "choro",
            "flamenco",
            "brazilian jazz",
            "middle eastern traditional",
            "belgian jazz",
            "jazz guitar",
            "jazz double bass",
            "thai traditional",
            "trad jazz catala",
            "polynesian traditional",
            "man's orchestra",
            "american folk revival",
            "central asian folk",
            "burmese traditional",
            "piano blues",
            "rwandan traditional",
            "sundanese traditional",
            "vintage italian pop",
            "israeli traditional",
            "new orleans jazz",
            "zither",
            "northumbrian folk",
            "jazz clarinet",
            "austrian jazz",
            "yunnan traditional",
            "flamenco guitar",
            "candomble",
            "argentine jazz",
            "korean traditional",
            "vintage broadway",
            "bossa nova",
            "klezmer",
            "mallet",
            "nova canco",
            "mountain dulcimer",
            "catalan folk",
            "vietnamese traditional",
            "old-time",
            "gong",
            "adult standards",
            "gospel blues",
            "nueva cancion",
            "australian jazz",
            "vintage tango",
            "space age pop",
            "balalaika",
            "haitian traditional",
            "vocal harmony group",
            "jazz tuba",
            "vintage hollywood",
            "swedish jazz",
            "mazandarani folk",
            "visor",
            "texas blues",
            "vintage spanish pop",
            "kyrgyz traditional",
            "sarod",
            "tango cancion",
            "zamba",
            "stride",
            "brazilian modern jazz",
            "lounge",
            "musicas espiritas",
            "kentucky mountain folk",
            "jazz guitar trio",
            "early american folk",
            "cornish folk",
            "bajki",
            "egyptian traditional",
            "traditional folk",
            "czech jazz",
            "danish jazz",
            "piano mpb",
            "dechovka",
            "indian violin",
            "cabaret",
            "bengali folk",
            "traditional blues",
            "vintage jazz",
            "bard",
            "swazi traditional",
            "vintage old-time",
            "lithuanian jazz",
            "appalachian folk",
            "french folk",
            "classical mandolin",
            "folclore navarra",
            "piedmont blues",
            "veena",
            "irish folk",
            "dixieland",
            "vintage norwegian pop",
            "italian jazz",
            "movie tunes",
            "polish jazz",
            "boogie-woogie",
            "exotica",
            "latin classical",
            "welsh folk",
            "guitarra portuguesa",
            "kora",
            "nuevo tango",
            "arab folk",
            "classic female blues",
            "jug band",
            "jaw harp",
            "dutch jazz",
            "barrelhouse piano",
            "deep free jazz",
            "hindustani instrumental",
            "israeli jazz",
            "british jazz",
            "indian classical",
            "cimbalom",
            "calypso",
            "bandoneon",
            "hot jazz",
            "sean-nos singing",
            "british folk",
            "traditional english folk",
            "vintage schlager",
            "icelandic jazz",
            "vintage swedish pop",
            "uzbek traditional",
            "musica yucateca",
            "folklore surero",
            "country blues",
            "jazz harp",
            "vintage hawaiian",
            "german jazz",
            "swiss jazz",
            "gypsy",
            "jazz organ",
            "trova",
            "beat poetry",
            "torch song",
            "bolero mexicano",
            "orquesta tipica",
            "modern swing",
            "dombra",
            "yorkshire folk",
            "traditional british folk",
            "bothy ballad",
            "carnatic instrumental",
            "blasmusik",
            "jazz composition",
            "deep vocal jazz",
            "acoustic blues",
            "blaskapelle",
            "tar",
            "copla",
            "jazz accordion",
            "vintage country folk",
            "carnatic",
            "korean jazz",
            "pygmy music",
            "indonesian indigenous traditional",
            "ancient mediterranean",
            "canadian modern jazz",
            "delta blues",
            "soul",
            "moroccan traditional",
            "fingerstyle",
            "thai instrumental",
            "balinese traditional",
            "folklore cuyano",
            "blues",
            "children's story",
            "irish modern jazz",
            "folklore argentino",
            "library music",
            "velha guarda",
            "classical clarinet",
            "fado instrumental",
            "latin jazz",
            "canto popular uruguayo",
            "cante alentejano",
            "spiritual jazz",
            "tanzanian"
        ]

        # Top 300-ish Genres Related to Rock
        rock_genres = [
            "rock",
            "album rock",
            "classic rock",
            "heartland rock",
            "hard rock",
            "permanent wave",
            "soft rock",
            "mellow gold",
            "alternative rock",
            "modern rock",
            "glam rock",
            "alternative metal",
            "nu metal",
            "singer-songwriter",
            "folk rock",
            "glam metal",
            "blues rock",
            "country rock",
            "southern rock",
            "post-grunge",
            "psychedelic rock",
            "classic hungarian rock",
            "deathgrass",
            "beatlesque",
            "british blues",
            "czech rock",
            "classic canadian rock",
            "slovenian rock",
            "freakbeat",
            "voetbal",
            "blues latinoamericano",
            "japanese blues",
            "argentine rock",
            "australian rock",
            "asbury park indie",
            "protopunk",
            "power blues-rock",
            "pinoy alternative rock",
            "twin cities indie",
            "finnish blues",
            "columbus ohio indie",
            "swedish blues",
            "indonesian blues",
            "icelandic rock",
            "german rock",
            "rock andaluz",
            "yugoslav rock",
            "jangle pop",
            "eugene indie",
            "praise",
            "north alabama indie",
            "kingston on indie",
            "rock gaucho",
            "folk punk",
            "power pop",
            "galego",
            "san marcos tx indie",
            "polish rock",
            "rock quebecois",
            "grand rapids indie",
            "kent indie",
            "stl indie",
            "suomi rock",
            "zolo",
            "alternative roots rock",
            "brazilian blues",
            "russian rock",
            "deep classic garage rock",
            "bisrock",
            "rock uruguayo",
            "rock baiano",
            "brno indie",
            "rock sergipano",
            "dutch blues",
            "art punk",
            "knoxville indie",
            "tarantella",
            "modern blues rock",
            "pub rock",
            "peruvian rock",
            "rock urbano mexicano",
            "contemporary gospel",
            "modern blues",
            "euskal rock",
            "belgian blues",
            "classic finnish rock",
            "rochester ny indie",
            "musiikkia lapista",
            "polish blues",
            "classic danish rock",
            "alabama indie",
            "celtic rock",
            "classic russian rock",
            "bulgarian rock",
            "indie canario",
            "oc indie",
            "australian rockabilly",
            "piano rock",
            "lo star",
            "chicago indie",
            "albany ny indie",
            "beach music",
            "lafayette indie",
            "finnish new wave",
            "omaha indie",
            "steampunk",
            "orlando indie",
            "dutch rock",
            "lexington ky indie",
            "slovak pop",
            "pinoy rock",
            "rock nacional brasileiro",
            "rock drums",
            "bay area indie",
            "classic garage rock",
            "brazilian rockabilly",
            "halifax indie",
            "scottish new wave",
            "brazilian rock",
            "italian alternative",
            "kc indie",
            "indiana indie",
            "new hampshire indie",
            "hamilton on indie",
            "wyoming indie",
            "garage punk blues",
            "russian folk rock",
            "hawaiian indie",
            "pittsburgh indie",
            "psychedelic blues-rock",
            "ecuadorian alternative rock",
            "ok indie",
            "polish post-punk",
            "turkish punk",
            "southampton indie",
            "underground power pop",
            "british invasion",
            "fort wayne indie",
            "rock caipira",
            "rogaland indie",
            "classic bulgarian pop",
            "north east england indie",
            "western mass indie",
            "yugoslav new wave",
            "medway sound",
            "hamburger schule",
            "streektaal",
            "gypsy punk",
            "macedonian rock",
            "isle of wight indie",
            "russian alternative rock",
            "paisley underground",
            "austindie",
            "dc indie",
            "olympia wa indie",
            "classic j-rock",
            "musica pitiusa",
            "wisconsin indie",
            "french rockabilly",
            "bangladeshi rock",
            "croatian indie",
            "indie nordeste argentino",
            "one-person band",
            "rhode island indie",
            "rock paraibano",
            "croatian rock",
            "balkan post-punk",
            "indie cantabria",
            "rock catracho",
            "nova musica amazonense",
            "arkansas indie",
            "lincoln ne indie",
            "dallas indie",
            "detroit indie",
            "deep christian rock",
            "dutch indie",
            "irish rock",
            "serbian alternative rock",
            "rva indie",
            "musica campista",
            "rock potiguar",
            "lawrence ks indie",
            "athens indie",
            "kentucky indie",
            "perth indie",
            "musica aragonesa",
            "indie poblano",
            "art rock",
            "dark cabaret",
            "tape club",
            "hamburg indie",
            "naija worship",
            "milwaukee indie",
            "ontario indie",
            "chilean rock",
            "serbian indie",
            "spanish blues",
            "kyushu indie",
            "ny roots",
            "springfield mo indie",
            "worcester ma indie",
            "rogaland musikk",
            "edmonton indie",
            "belgian rock",
            "portuguese rock",
            "bergamo indie",
            "rotterdam indie",
            "twee pop",
            "canadian indie",
            "baton rouge indie",
            "missouri indie",
            "deep indie pop",
            "queercore",
            "victoria bc indie",
            "albuquerque indie",
            "puerto rican indie",
            "gainesville indie",
            "swiss rock",
            "connecticut indie",
            "charlotte nc indie",
            "ann arbor indie",
            "little rock indie",
            "michigan indie",
            "canadian psychedelic",
            "canadian blues",
            "indie rock",
            "bosstown sound",
            "buffalo ny indie",
            "norwegian blues",
            "south carolina indie",
            "south african gospel",
            "rock kapak",
            "alternative"
        ]

        # Top 300-ish Genres Related to Classical
        classical_genres = [
            "classical",
            "early modern classical",
            "early music",
            "late romantic era",
            "neoclassicism",
            "post-romantic era",
            "baroque",
            "german romanticism",
            "classical era",
            "classical performance",
            "russian romanticism",
            "early romantic era",
            "impressionism",
            "french opera",
            "french romanticism",
            "italian romanticism",
            "renaissance",
            "contemporary classical",
            "avant-garde",
            "italian opera",
            "italian baroque",
            "australian classical",
            "viola",
            "japanese classical performance",
            "korean classical performance",
            "chamber ensemble",
            "oriental classical",
            "portuguese classical",
            "french renaissance",
            "israeli classical",
            "russian modern classical",
            "irish classical",
            "hungarian classical performance",
            "english renaissance",
            "classical drill",
            "classical flute",
            "string quartet",
            "chamber orchestra",
            "classical piano trio",
            "portuguese contemporary classical",
            "classical cello",
            "danish classical",
            "hungarian contemporary classical",
            "chinese classical performance",
            "romanian contemporary classical",
            "classical horn",
            "quatuor a cordes",
            "early music ensemble",
            "fictitious orchestra",
            "classical oboe",
            "dutch contemporary classical",
            "spanish renaissance",
            "czech contemporary classical",
            "galante era",
            "orchestral performance",
            "classical bassoon",
            "russian contemporary classical",
            "contrabass",
            "american contemporary classical",
            "austro-german modernism",
            "xenharmonic",
            "classical trombone",
            "orthodox chant",
            "danish contemporary classical",
            "viola da gamba",
            "minimalism",
            "spanish contemporary classical",
            "balkan classical piano",
            "medieval",
            "american modern classical",
            "british classical piano",
            "lds instrumental",
            "american 21st century classical",
            "turkish classical performance",
            "portuguese early music",
            "czech classical",
            "american romanticism",
            "modern string quartet",
            "radio symphony",
            "belgian contemporary classical",
            "german baroque",
            "latin american baroque",
            "chinese classical",
            "violin",
            "mexican classical",
            "british contemporary classical",
            "classical saxophone",
            "italian contemporary classical",
            "serialism",
            "streichquartett",
            "norwegian classical",
            "english baroque",
            "german orchestra",
            "bohemian baroque",
            "dutch baroque",
            "baroque brass",
            "canadian contemporary classical",
            "gregorian chant",
            "australian classical piano",
            "japanese contemporary classical",
            "polish contemporary classical",
            "swiss contemporary classical",
            "compositional ambient",
            "native american flute",
            "shakuhachi",
            "wind symphony",
            "icelandic classical",
            "string orchestra",
            "baroque ensemble",
            "french baroque",
            "caucasian classical",
            "historically informed performance",
            "spanish classical piano",
            "baroque woodwind",
            "barockinterpreten",
            "post-minimalism",
            "concert band",
            "japanese classical piano",
            "historic piano performance",
            "french orchestra",
            "taiwan classical performance",
            "classical piano quartet",
            "classical string trio",
            "nordic classical piano",
            "brazilian classical",
            "historic string quartet",
            "austrian orchestra",
            "recorder",
            "chinese classical piano",
            "canadian classical",
            "irish contemporary classical",
            "modern performance",
            "21st century classical",
            "german renaissance",
            "cello ensemble",
            "ukrainian classical piano",
            "glass",
            "musica antigua",
            "american early music",
            "wind quintet",
            "italian violin",
            "victorian britain",
            "spanish baroque",
            "italian renaissance",
            "swiss classical piano",
            "spanish classical",
            "korean classical piano",
            "british modern classical",
            "swedish contemporary classical",
            "british brass band",
            "new zealand classical",
            "czech classical piano",
            "russian orchestra",
            "historic orchestral performance",
            "german contemporary classical",
            "classical tuba",
            "orkiestra symfoniczna",
            "contemporary classical piano",
            "latin american classical piano",
            "puirt-a-beul",
            "brazilian contemporary classical",
            "caucasian classical piano",
            "classical piano",
            "ukrainian classical",
            "italian baroque ensemble",
            "medieval ensemble",
            "chinese wind",
            "nordic orchestra",
            "austrian classical piano",
            "baltic classical piano",
            "historical keyboard",
            "italian orchestra",
            "japanese piano",
            "classical saxophone quartet",
            "italian classical piano",
            "brass ensemble",
            "japanese classical",
            "romanian classical piano",
            "dutch classical piano",
            "french contemporary classical",
            "pet calming",
            "staff band",
            "belgian classical piano",
            "german classical piano",
            "trombone ensemble",
            "swedish classical",
            "musique ancienne",
            "austrian contemporary classical",
            "polish classical",
            "baltic classical",
            "hengelliset laulut",
            "brass quintet",
            "nordic contemporary classical",
            "american orchestra",
            "french classical piano",
            "baroque violin",
            "light music",
            "euphonium",
            "baroque cello",
            "canadian classical piano",
            "classical harp",
            "operetta",
            "neo-classical",
            "british orchestra",
            "ukrainian contemporary classical",
            "trecento",
            "american classical piano",
            "polish early music",
            "hungarian classical piano",
            "modern chamber music",
            "cambridge choir",
            "russian classical piano",
            "austrian choir",
            "boy soprano",
            "wind ensemble",
            "israeli classical piano",
            "madrigal",
            "korean contemporary classical",
            "german opera",
            "tibetan mantra",
            "caucasian folk",
            "finnish classical",
            "quartetto d'archi",
            "polish classical piano",
            "minnesang"
        ]

        # Top 300-ish Genres Related to Reggae
        reggae_genres = [
            "reggae",
            "roots reggae",
            "dub",
            "rocksteady",
            "lovers rock",
            "old school dancehall",
            "modern reggae",
            "uk dub",
            "reggae fusion",
            "dancehall",
            "vintage reggae",
            "early reggae",
            "deep ragga",
            "traditional reggae",
            "uk reggae",
            "dub poetry",
            "seggae",
            "musica campechana",
            "vanuatu music",
            "finnish reggae",
            "tamaulipas rap",
            "bases de freestyle",
            "swiss reggae",
            "comedy rap",
            "rap nacional antigo",
            "reggae tico",
            "guyanese pop",
            "virgin islands reggae",
            "irish drill",
            "african reggae",
            "uk drill",
            "marimba orquesta",
            "shatta",
            "musica tabasquena",
            "bornesange",
            "cumbia salvadorena",
            "surinamese hip hop",
            "melodic drill",
            "cumbia del sureste",
            "rap ecuatoriano",
            "jawaiian",
            "afro drill",
            "dutch drill",
            "rap df",
            "jamaican ska",
            "narco rap",
            "decije pesme",
            "rap maromba",
            "kenyan drill",
            "dennery segment",
            "rap ecuatoguineano",
            "preschool children's music",
            "afrikaans hip hop",
            "deep g funk",
            "nyahbinghi",
            "musica poblana",
            "pop catracho",
            "nederreggae",
            "ska jazz",
            "german viral rap",
            "swedish reggae",
            "gambian pop",
            "rap moldovenesc",
            "musica tropical guatemalteca",
            "kenyan hip hop",
            "cumbia colombiana regia",
            "dub brasileiro",
            "bayerischer rap",
            "dutch rap pop",
            "rap underground colombiano",
            "rap paraguayo",
            "hip hop boliviano",
            "reggae do maranhao",
            "jazz rap",
            "ritmo kombina",
            "german reggae",
            "rap gasy",
            "kids hip hop",
            "rap canario",
            "dancehall mauricien",
            "vaikiskos dainos",
            "sierra leonean pop",
            "bachchon ke geet",
            "seychelles pop",
            "musica istmena",
            "antilliaanse rap",
            "german boom bap",
            "rap femenino mexicano",
            "german jazz rap",
            "traditional ska",
            "speed up brasileiro",
            "swedish dancehall",
            "marimba mexicana",
            "maluku pop",
            "reggae en espanol",
            "dancehall guyanaise",
            "aussie drill",
            "trap funk",
            "nz reggae",
            "children's music",
            "virginia hip hop",
            "british children's music",
            "rap salvadoreno",
            "asakaa",
            "liberian pop",
            "pinoy alternative rap",
            "nephop",
            "gengetone",
            "dutch hip hop",
            "kwaito",
            "reggae tuga",
            "detske pesnicky",
            "gospel drill",
            "dirty texas rap",
            "post-disco soul",
            "mexican hip hop",
            "musica chiapaneca",
            "malaysian tamil rap",
            "south sudanese pop",
            "scouse rap",
            "cançoes infantis",
            "ethiopian hip hop",
            "rap gabonais",
            "gambian hip hop",
            "reggae mexicano",
            "muzica copii",
            "argentine reggae",
            "popping",
            "khmer hip hop",
            "punjabi hip hop",
            "hip hop reunionnais",
            "reunion pop",
            "chill drill",
            "raspe",
            "ghanaian pop",
            "russian pixel",
            "trap peruano",
            "cumbia ecuatoriana",
            "ghanaian alternative",
            "hip hop timur",
            "frauenrap",
            "marimba de guatemala",
            "rap uruguayo",
            "colombian hip hop",
            "detskie pesni",
            "pinoy hip hop",
            "southern soul blues",
            "reggae peruano",
            "boom bap brasileiro",
            "drill dominicano",
            "rap boricua",
            "kentucky hip hop",
            "lithuanian hip hop",
            "dutch trap",
            "pakistani hip hop",
            "nu-cumbia",
            "romanian rap",
            "rap underground mexicano",
            "brazilian hip hop",
            "rap nica",
            "trap colombiano",
            "trap boliviano",
            "musica hondurena",
            "trap mexicano",
            "scottish drill",
            "ugandan hip hop",
            "scratch",
            "nz gangsta rap",
            "hamburg hip hop",
            "muziek voor kinderen",
            "argentine hip hop",
            "bay area hip hop",
            "somali pop",
            "vlaamse rap",
            "trap pesado",
            "musique urbaine brazzaville",
            "chicano rap",
            "german drill",
            "schweizer rap",
            "sudanese hip hop",
            "urbano mexicano",
            "slovenian hip hop",
            "north carolina hip hop",
            "cumbia sonidera",
            "houston rap",
            "nottingham hip hop",
            "gospel reggae",
            "luxembourgian hip hop",
            "bulgarian hip hop",
            "rap sardegna",
            "atlanta bass",
            "chopped and screwed",
            "macedonian hip hop",
            "mongolian hip hop",
            "urdu hip hop",
            "cartoon",
            "rap tico",
            "telugu hip hop",
            "finnish drill"
        ]

        # Top 300-ish Genres Related to Lo-fi
        lofi_genres = [
            "lo-fi",
            "gbvfi",
            "noise pop",
            "indie rock",
            "alternative rock",
            "elephant 6",
            "chamber pop",
            "slowcore",
            "alternative pop",
            "experimental rock",
            "noise rock",
            "dunedin sound",
            "anti-folk",
            "tape club",
            "experimental indie rock",
            "dunedin indie",
            "neo-psicodelia brasileira",
            "olympia wa indie",
            "lo-fi emo",
            "norman ok indie",
            "idaho indie",
            "western mass indie",
            "ohio indie",
            "shanghai indie",
            "progressive rock",
            "washington indie",
            "new orleans indie",
            "spanish prog",
            "bay area indie",
            "finnish progressive rock",
            "classic psychedelic rock",
            "aarhus indie",
            "alabama indie",
            "pittsburgh indie",
            "bristol indie",
            "deep indie pop",
            "socal indie",
            "rhode island indie",
            "dutch prog",
            "french experimental rock",
            "eugene indie",
            "symphonic rock",
            "connecticut indie",
            "art rock",
            "lancaster pa indie",
            "wisconsin indie",
            "lawrence ks indie",
            "denton tx indie",
            "bath indie",
            "iowa indie",
            "psychedelic blues-rock",
            "north carolina indie",
            "buffalo ny indie",
            "melbourne indie",
            "louisville indie",
            "gothic americana",
            "omaha indie",
            "rochester ny indie",
            "cascadia psych",
            "new jersey indie",
            "boston indie",
            "memphis indie",
            "athens indie",
            "chicago indie",
            "triangle indie",
            "cornwall indie",
            "norrbotten indie",
            "prog quebec",
            "normal indie",
            "cardiff indie",
            "neo-psychedelic",
            "protopunk",
            "portland indie",
            "indie emo rock",
            "grand rapids indie",
            "calgary indie",
            "baton rouge indie",
            "alandsk musik",
            "tucson indie",
            "no wave",
            "flute rock",
            "celtic rock",
            "maine indie",
            "st petersburg fl indie",
            "acid rock",
            "canadian psychedelic",
            "japanese prog",
            "indiana indie",
            "rochester mn indie",
            "cambridgeshire indie",
            "fort wayne indie",
            "okc indie",
            "columbus ohio indie",
            "beatlesque",
            "dark cabaret",
            "rva indie",
            "rock progresivo mexicano",
            "canterbury scene",
            "nottingham indie",
            "dundee indie",
            "boston rock",
            "avant-rock",
            "singaporean indie",
            "hypnagogic pop",
            "lincoln ne indie",
            "derby indie",
            "milwaukee indie",
            "proto-metal",
            "mecha",
            "gainesville indie",
            "houston indie",
            "experimental pop",
            "oslo indie",
            "san antonio indie",
            "norwegian punk",
            "vancouver indie",
            "albany ny indie",
            "supergroup",
            "italian progressive rock",
            "north dakota indie",
            "seattle indie",
            "atlanta indie",
            "math rock",
            "oakland indie",
            "kc indie",
            "indie tabasqueno",
            "kingston on indie",
            "alternative roots rock",
            "lund indie",
            "missouri indie",
            "brazilian indie rock",
            "double drumming",
            "sheffield indie",
            "baltimore indie",
            "welsh indie",
            "toronto indie",
            "hurdy-gurdy",
            "asbury park indie",
            "freakbeat",
            "ok indie",
            "louisville underground",
            "instrumental rock",
            "orebro indie",
            "wellington indie",
            "san marcos tx indie",
            "nz indie",
            "dresden indie",
            "bury st edmunds indie",
            "estonian rock",
            "michigan indie",
            "aberdeen indie",
            "denver indie",
            "gothenburg indie",
            "dc indie",
            "knoxville indie",
            "southampton indie",
            "sacred steel",
            "brno indie",
            "irish rock",
            "bosstown sound",
            "duluth indie",
            "springfield mo indie",
            "tijuana indie",
            "dutch blues",
            "dayton indie",
            "new hampshire indie",
            "garage punk blues",
            "philly indie",
            "santa fe indie",
            "arkansas indie",
            "charlotte nc indie",
            "glam rock",
            "scottish indie",
            "dublin indie",
            "nashville singer-songwriter",
            "rogaland indie",
            "malmo indie",
            "tassie indie",
            "norwegian prog",
            "rock keyboard",
            "shimmer psych",
            "belfast indie",
            "rotterdam indie",
            "classic hungarian rock",
            "belgian indie rock",
            "hampton roads indie",
            "austindie",
            "twee indie pop",
            "british blues",
            "album rock",
            "trondheim indie",
            "ontario indie",
            "pittsburgh indie rock",
            "indy indie",
            "stl indie",
            "newcastle indie",
            "rock progressif francais",
            "umea indie",
            "quebec indie",
            "victoria bc indie",
            "zolo",
            "jangle pop",
            "scottish hush",
            "west virginia indie",
            "indie poblano",
            "tulum",
            "dream pop",
            "south dakota indie",
            "one-person band",
            "palm desert scene",
            "rock",
            "ottawa indie",
            "brooklyn indie",
            "synth prog",
            "indie trujillano",
            "newcastle nsw indie",
            "kansas indie",
            "japanese psychedelic",
            "paisley underground",
            "japanese celtic",
            "german prog",
            "basel indie",
            "dutch indie",
            "nashville indie",
            "dalarna indie",
            "stockholm indie",
            "mississippi indie",
            "wyoming indie",
            "twee pop",
            "steampunk",
            "solo wave",
            "progressive jazz fusion",
            "twin cities indie",
            "christchurch indie",
            "collage pop",
            "south carolina indie",
            "lo-fi vgm"
        ]

        # Top 300-ish Genres Related to Anime
        anime_genres = [
            "anime",
            "seiyu",
            "j-pixie",
            "anime rock",
            "j-pop",
            "j-rock",
            "bogor indie",
            "balikpapan indie",
            "indonesian pop punk",
            "northern irish indie",
            "warrington indie",
            "taiwan rock",
            "indie rock peruano",
            "anime cv",
            "spanish modern rock",
            "reading indie",
            "glasgow indie",
            "indie rock mexicano",
            "bandung indie",
            "granada indie",
            "australian indie rock",
            "sevilla indie",
            "manchester indie",
            "english indie rock",
            "south african rock",
            "tempe indie",
            "japanese alternative rock",
            "medieval rock",
            "german indie rock",
            "malaysian indie",
            "swiss alternative rock",
            "yaoi",
            "scottish indie rock",
            "canadian rock",
            "polish indie rock",
            "k-rock",
            "indonesian rock",
            "modern rock",
            "varmland rock",
            "spanish noise pop",
            "spanish indie pop",
            "modern alternative rock",
            "indie valenciana",
            "korean indie rock",
            "polish alternative rock",
            "musica maringaense",
            "japanese indie rock",
            "kiwi rock",
            "rock cearense",
            "british indie rock",
            "san diego indie",
            "german alternative rock",
            "stomp pop",
            "rock tico",
            "hokkaido indie",
            "indie surf",
            "indie veneto",
            "britpop",
            "welsh rock",
            "indie rock colombiano",
            "leicester indie",
            "frankfurt indie",
            "sydney indie",
            "la indie",
            "dortmund indie",
            "j-indie",
            "murcia indie",
            "uppsala indie",
            "indie arequipeno",
            "hull indie",
            "hungarian rock",
            "poznan indie",
            "indie rock italiano",
            "miami indie",
            "dansei seiyu",
            "novo rock gaucho",
            "malang indie",
            "post-punk brasileiro",
            "gotico brasileiro",
            "magyar alternative",
            "tamaulipas indie",
            "windsor on indie",
            "tulsa indie",
            "christian alternative rock",
            "greek rock",
            "shojo",
            "bali indie",
            "brighton indie",
            "j-poprock",
            "kansai indie",
            "modern uplift",
            "danish rock",
            "scottish rock",
            "northamptonshire indie",
            "semarang indie",
            "liverpool indie",
            "birmingham indie",
            "leeds indie",
            "rock catarinense",
            "brisbane indie",
            "rock cristiano",
            "indie pop rock",
            "portsmouth indie",
            "rock alternativo espanol",
            "madchester",
            "yogyakarta indie",
            "worcester ma indie",
            "hungarian indie",
            "german post-punk",
            "phoenix indie",
            "crank wave",
            "deep indie rock",
            "rock sul-mato-grossense",
            "vegas indie",
            "doujin",
            "indie cantabria",
            "coventry indie",
            "dutch indie rock",
            "argentine alternative rock",
            "latvian rock",
            "sonora indie",
            "romanian punk",
            "russian indie rock",
            "slc indie",
            "nice indie",
            "euskal indie",
            "essex indie",
            "scenecore",
            "heavy gothic rock",
            "north east england indie",
            "orlando indie",
            "rosario indie",
            "sacramento indie",
            "brooklyn indie",
            "russian alternative rock",
            "uk post-punk revival",
            "chinese indie rock",
            "firenze indie",
            "surabaya indie",
            "modern jangle pop",
            "australian surf rock",
            "edinburgh indie",
            "newcastle nsw indie",
            "sardinia indie",
            "argentine indie rock",
            "merida indie",
            "kyushu indie",
            "grebo",
            "lithuanian rock",
            "indie garage rock",
            "south borneo indie",
            "wyoming indie",
            "hard chime",
            "auckland indie",
            "japanese post-punk",
            "bergamo indie",
            "london indie",
            "rock chapin",
            "svensk indie",
            "orebro indie",
            "adelaide indie",
            "pixie",
            "oxford indie",
            "hong kong rock",
            "baltic post-punk",
            "italian post-punk",
            "rock alternativo brasileiro",
            "irish indie rock",
            "spanish post-punk",
            "pop rock",
            "tontipop",
            "cincinnati indie",
            "classic j-rock",
            "swedish indie rock",
            "classic indonesian rock",
            "touhou",
            "indonesian alternative rock",
            "south dakota indie",
            "london on indie",
            "ottawa indie",
            "neue deutsche todeskunst",
            "permanent wave",
            "turkish punk",
            "indonesian indie rock",
            "rock independant francais",
            "ecuadorian alternative rock",
            "panamanian rock",
            "detroit indie",
            "modern mod",
            "euskal rock",
            "swedish post-punk",
            "alternative pop rock",
            "indie rockism",
            "finnish alternative rock",
            "indie extremena",
            "modern downshift",
            "emo mexicano",
            "scottish indie",
            "indie queretano",
            "turin indie",
            "east anglia indie",
            "brazilian emo",
            "kelowna bc indie",
            "anime latino",
            "san antonio indie",
            "swedish alternative rock",
            "fort worth indie",
            "rock alagoano",
            "rotterdam indie",
            "monterrey indie",
            "serbian indie",
            "rebel blues",
            "polish post-punk",
            "indie trujillano",
            "kansas indie",
            "charlotte nc indie",
            "portuguese indie rock",
            "post-punk latinoamericano",
            "synth punk",
            "russian nu metal",
            "classic j-pop",
            "stockholm indie",
            "basel indie",
            "dundee indie"
        ]

        # Top 300-ish Genres Related to Video Game Music
        video_game_music_genres = [
        "video game music",
        "indie game soundtrack",
        "orchestral soundtrack",
        "polish ambient",
        "dreampunk",
        "space ambient",
        "experimental synth",
        "scorecore",
        "australian experimental",
        "indian ambient",
        "dark jazz",
        "new isolationism",
        "mandible",
        "horror synth",
        "comfy synth",
        "dark ambient",
        "japanese soundtrack",
        "experimental ambient",
        "italian experimental",
        "spanish experimental",
        "italian post-rock",
        "middle earth",
        "australian ambient",
        "berlin school",
        "nordic ambient",
        "abstractro",
        "danish experimental",
        "ambient",
        "new england experimental",
        "canadian experimental",
        "ambient worship",
        "hauntology",
        "modular synth",
        "halloween",
        "spectra",
        "korean soundtrack",
        "ambient pop",
        "fantasy",
        "dungeon synth",
        "turkish experimental",
        "synthesizer",
        "german soundtrack",
        "iranian experimental",
        "argentine ambient",
        "nordic soundtrack",
        "ritual ambient",
        "chinese soundtrack",
        "polish experimental",
        "icelandic experimental",
        "cinematic post-rock",
        "ai",
        "italian occult psychedelia",
        "bulgarian experimental",
        "swedish experimental",
        "ambient lo-fi",
        "belgian experimental",
        "fourth world",
        "dutch experimental",
        "norwegian experimental",
        "anime score",
        "post-rock",
        "czech experimental",
        "canadian post-rock",
        "j-ambient",
        "arab experimental",
        "neoclassical darkwave",
        "irish experimental",
        "ambient industrial",
        "totalism",
        "kundalini",
        "cello",
        "british post-rock",
        "turkish soundtrack",
        "synthetic classical",
        "portuguese post-rock",
        "american post-rock",
        "ambient guitar",
        "portuguese experimental",
        "new age",
        "pilates",
        "british soundtrack",
        "cosmic post-rock",
        "modern electroacoustic",
        "instrumental post-rock",
        "korean experimental",
        "tennessee experimental",
        "latin soundtrack",
        "drone",
        "drone psych",
        "theremin",
        "oceania soundtrack",
        "slushwave",
        "ambient post-rock",
        "mexican experimental",
        "ambient country",
        "experimental psych",
        "japanese vgm",
        "brazilian post-rock",
        "dark folk",
        "chinese post-rock",
        "australian post-rock",
        "epicore",
        "finnish experimental",
        "theme",
        "8d",
        "canadian soundtrack",
        "indonesian experimental",
        "keller synth",
        "peruvian experimental",
        "nu age",
        "commons",
        "nordic post-rock",
        "soundtrack",
        "pastoral",
        "experimental folk",
        "neofolk",
        "belgian post-rock",
        "british experimental",
        "sound art",
        "atmospheric post-rock",
        "vintage italian soundtrack",
        "martial industrial",
        "liechtenstein",
        "italian soundtrack",
        "french soundtrack",
        "electroacoustic improvisation",
        "bagpipe marching band",
        "rune folk",
        "taiwan instrumental",
        "modern cello",
        "krautrock",
        "duduk",
        "african experimental",
        "chapman stick",
        "deep soundtrack",
        "ukrainian contemporary classical",
        "slowcore",
        "bow pop",
        "experimental percussion",
        "ethereal wave",
        "lowercase",
        "polish experimental electronic",
        "indian instrumental rock",
        "epic collage",
        "experimental guitar",
        "pop violin",
        "french post-rock",
        "taiwan post-rock",
        "arabic instrumental",
        "zampogna",
        "free folk",
        "moog",
        "glitch",
        "broken transmission",
        "ambient synth",
        "utopian virtual",
        "japanese classical",
        "polish psychedelia",
        "japanese orchestra",
        "abstract",
        "musica evangelica instrumental",
        "drone rock",
        "scottish smallpipe",
        "deep ambient",
        "taiwan experimental",
        "chinese experimental",
        "viking folk",
        "laboratorio",
        "italian industrial",
        "classic nepali pop",
        "polish post-rock",
        "post-rock latinoamericano",
        "native american traditional",
        "raga rock",
        "lo-fi indie",
        "british electroacoustic",
        "modern psychedelic folk",
        "ukrainian experimental",
        "russian modern jazz",
        "musique pour enfants",
        "prepared piano",
        "classical piano quartet",
        "brazilian experimental",
        "russian post-rock",
        "japanese concert band",
        "thai post-rock",
        "italian library music",
        "minneapolis indie",
        "mexican post-rock",
        "hardvapour",
        "german post-rock",
        "christelijk",
        "microtonal",
        "pop ambient",
        "pops orchestra",
        "world meditation",
        "new tribe",
        "tibetan mantra",
        "medieval folk",
        "uk experimental electronic",
        "ambient idm",
        "new weird finland",
        "italian modern prog",
        "police band",
        "classic soundtrack",
        "vintage french electronic",
        "experimental jazz",
        "japanese celtic",
        "tzadik",
        "rock in opposition",
        "mallsoft",
        "alphorn",
        "experimental",
        "pinoy shoegaze",
        "sound team",
        "cascadia psych",
        "british orchestra",
        "string duo",
        "norwegian contemporary jazz",
        "korean ost",
        "drone folk",
        "german prog",
        "bagpipe",
        "lullaby",
        "synth prog",
        "israeli folk",
        "psychedelic jazz fusion",
        "japanese psychedelic",
        "american primitive",
        "rock progresivo mexicano",
        "southeast asian post-rock",
        "chinese instrumental",
        "dub metal",
        "norwegian jazz",
        "vgm instrumental",
        "abstract idm",
        "cocuk sarkilari",
        "musica sinfonica",
        "japanese post-rock",
        "turkish post-punk",
        "tassie indie",
        "rock keyboard",
        "rock progressif francais",
        "hypertrance",
        "british industrial",
        "lo-fi vgm"
    ]

        GENRES = [pop_genres, 
                rap_genres, 
                edm_genres, 
                country_genres, 
                jazz_genres, 
                rock_genres, 
                classical_genres, 
                reggae_genres,
                lofi_genres,
                anime_genres,
                video_game_music_genres]
        
        return GENRES