//Default layout so that page does not look empty
export const defaultLayout = [
  {
    h: 1,
    i: "Top songs of last 4 weeks",
    w: 2,
    x: 0,
    y: 0,
    data: "top_songs_4week",
    graphType: "ImageGraph",
    graphSettings: {},
  },
  {
    h: 1,
    i: "Top Artists of last 4 weeks",
    w: 2,
    x: 0,
    y: 3,
    data: "top_artists_4week",
    graphType: "ImageGraph",
    graphSettings: {},
  },
  {
    h: 1,
    i: "Recent songs",
    w: 3,
    x: 2,
    y: 0,
    data: "recent_songs",
    graphType: "ImageGraph",
    graphSettings: {},
  },
  {
    h: 1,
    i: "Saved Songs",
    w: 1,
    x: 4,
    y: 1,
    data: "saved_songs",
    graphType: "ImageGraph",
    graphSettings: {},
  },
  {
    h: 1,
    i: "Followed Artists",
    w: 2,
    x: 2,
    y: 1,
    data: "followed_artists",
    graphType: "ImageGraph",
    graphSettings: {},
  },
  {
    h: 1,
    i: "Saved Albums",
    w: 2,
    x: 0,
    y: 2,
    data: "saved_albums",
    graphType: "ImageGraph",
    graphSettings: {},
  },
  {
    i: "Sample Pie",
    graphType: "Pie",
    data: "pie1",
    graphSettings: { graphTheme: "category10" },
    x: 3,
    y: 2,
    w: 1,
    h: 1,
  },
  {
    i: "Sample Bar",
    graphType: "Bar",
    data: "bar1",
    graphSettings: {
      graphKeys: ["degrees"],
      graphIndexBy: "day",
      graphTheme: "category10",
    },
    x: 2,
    y: 2,
    w: 1,
    h: 1,
  },
  {
    i: "Followers",
    graphType: "Line",
    data: "followers",
    graphSettings: {
      xName: "date",
      yName: "Followers",
      graphTheme: "spectral",
    },
    x: 4,
    y: 2,
    w: 1,
    h: 1,
  },
  {
    i: "Saved Playlists",
    graphType: "ImageGraph",
    data: "saved_playlists",
    graphSettings: {},
    x: 0,
    y: 1,
    w: 2,
    h: 1,
  },
];

export default defaultLayout;
